tls:
  certificates:
    - certFile: /certs/localhost+2.pem
      keyFile: /certs/localhost+2-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/localhost+2.pem
        keyFile: /certs/localhost+2-key.pem
  options:
    default:
      minVersion: VersionTLS13