entryPoints:
  websecure:
    address: ":443"
    http:
      tls: {}
      #http2:
      #  maxConcurrentStreams: 250

providers:
  docker:
    exposedByDefault: false
    network: mcp-network
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: /etc/traefik/certs.yml

api:
  dashboard: true
  insecure: true

tls:
  certificates:
    - certFile: /certs/localhost+2.pem
      keyFile: /certs/localhost+2-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/localhost+2.pem
        keyFile: /certs/localhost+2-key.pem
  options:
    default:
      minVersion: VersionTLS13
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256

log:
  level: DEBUG